# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: learning_data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13learning_data.proto\"=\n\x04\x44\x61ta\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x12\t\n\x01z\x18\x03 \x01(\x05\x12\x14\n\x0cplayer_state\x18\x04 \x01(\t\"\x1f\n\rModelResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2:\n\x0c\x44\x61taTransfer\x12*\n\x0fSendDataToModel\x12\x05.Data\x1a\x0e.ModelResponse\"\x00\x42\x17\n\x15io.grpc.data_transferb\x06proto3')



_DATA = DESCRIPTOR.message_types_by_name['Data']
_MODELRESPONSE = DESCRIPTOR.message_types_by_name['ModelResponse']
Data = _reflection.GeneratedProtocolMessageType('Data', (_message.Message,), {
  'DESCRIPTOR' : _DATA,
  '__module__' : 'learning_data_pb2'
  # @@protoc_insertion_point(class_scope:Data)
  })
_sym_db.RegisterMessage(Data)

ModelResponse = _reflection.GeneratedProtocolMessageType('ModelResponse', (_message.Message,), {
  'DESCRIPTOR' : _MODELRESPONSE,
  '__module__' : 'learning_data_pb2'
  # @@protoc_insertion_point(class_scope:ModelResponse)
  })
_sym_db.RegisterMessage(ModelResponse)

_DATATRANSFER = DESCRIPTOR.services_by_name['DataTransfer']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\025io.grpc.data_transfer'
  _DATA._serialized_start=23
  _DATA._serialized_end=84
  _MODELRESPONSE._serialized_start=86
  _MODELRESPONSE._serialized_end=117
  _DATATRANSFER._serialized_start=119
  _DATATRANSFER._serialized_end=177
# @@protoc_insertion_point(module_scope)
